springdoc:
  paths-to-exclude: /swagger-resources/**
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /portal-ms
